### ISSUE TITLE
Prepare development guide

### ISSUE THREAD

**Issue by Mini256** [Mini256/tidb-snowflake-e-commerce-demo#1]
## TODO

- [x] Basic usage of TIDB Cloud
- [x] Basic usage of Snowflake
- [x] Basic usage of ETLeap
- [x] How to startup this demo

**Comment by Mini256** [comment]
[Step by step guide](https://github.com/Mini256/tidb-snowflake-e-commerce-demo/tree/main/docs) has been ready. Thanks to @shczhen.
