### ISSUE TITLE
User experience improvement

### ISSUE THREAD

**Issue by Mini256** [Mini256/tidb-snowflake-e-commerce-demo#2]
## TODO

- [x] Support dynamically configurable data sources
- [x] Display the import process of the initial data and the speed of incremental data
- [x] Build the front-end page of E-commerce-demo
